layout_spectrum: 0.5680851
color:
  saturation: 0.1531915
  brandStrength: 0.8599294
  lightness: 0.01276596
  rhythmicContrast: 0.5234042
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.2234043
name: 'Stephanie Potter '
